{{- if .Values.rds.enabled }}
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: {{ .Values.rds.name }}
spec:

  forProvider:
    allocatedStorage: {{ .Values.rds.forProvider.allocatedStorage }}
    autoMinorVersionUpgrade: {{ .Values.rds.forProvider.autoMinorVersionUpgrade }}
    backupRetentionPeriod: {{ .Values.rds.forProvider.backupRetentionPeriod }}
    caCertificateIdentifier: {{ .Values.rds.forProvider.caCertificateIdentifier }}
    dbInstanceClass: {{ .Values.rds.forProvider.dbInstanceClass }}
    deletionProtection: {{ .Values.rds.forProvider.deletionProtection }}
    enableIAMDatabaseAuthentication: {{ .Values.rds.forProvider.enableIAMDatabaseAuthentication }}
    engine: {{ .Values.rds.forProvider.engine }}
    engineVersion: {{ .Values.rds.forProvider.engineVersion | quote }}
    masterUsername: {{ .Values.rds.forProvider.masterUsername }}
    multiAZ: {{ .Values.rds.forProvider.multiAZ }}
    port: {{ .Values.rds.forProvider.port }}
    publiclyAccessible: {{ .Values.rds.forProvider.publiclyAccessible }}
    region: {{ .Values.rds.forProvider.region }}
    storageEncrypted: {{ .Values.rds.forProvider.storageEncrypted }}
    storageType: {{ .Values.rds.forProvider.storageType }}
  providerConfigRef:
    name: {{ .Values.rds.providerConfigRefName }}
{{- end }}
